apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-baremetal-operator
  namespace: openshift-machine-api
  annotations:
    capability.openshift.io/name: baremetal
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
