---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-baremetal-operator-images
  namespace: openshift-machine-api
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
data:
  images.json: >
    {
      "clusterBaremetalOperator": "registry.ci.openshift.org/openshift:cluster-baremetal-operator",
      "kubeRBACProxy": "registry.ci.openshift.org/openshift:kube-rbac-proxy",
      "baremetalOperator": "registry.ci.openshift.org/openshift:baremetal-operator",
      "baremetalIronic": "registry.ci.openshift.org/openshift:ironic",
      "baremetalIronicInspector": "registry.ci.openshift.org/openshift:ironic-inspector",
      "baremetalIpaDownloader": "registry.ci.openshift.org/openshift:ironic-ipa-downloader",
      "baremetalMachineOsDownloader": "registry.ci.openshift.org/openshift:ironic-machine-os-downloader",
      "baremetalStaticIpManager": "registry.ci.openshift.org/openshift:ironic-static-ip-manager"
    }

