commonAnnotations:
  include.release.openshift.io/ibm-cloud-managed: "true"
  include.release.openshift.io/hypershift: "true"
  include.release.openshift.io/single-node-developer: "true"
  capability.openshift.io/name: baremetal

resources:
- cluster-baremetal-operator-hostedcluster.yaml
